#pragma once

#define CONSOLE_CREATE_SPRITE "MAKESPR"
//#define SPRITECREATE_COMMAND(x) MATCH(CONSOLE_CREATE_SPRITE, x){	ADDSPRITE}
#define CONSOLE_CREATE_BACKGROUND "CHGBACKGR"
#define CONSOLE_CHANGE_MUSIC "CHGMUSIC"
#define CONSOLE_STOP_MUSIC "CHGMUSIC"
#define CONSOLE_LOAD_SCRIPT "LOADSCRIPT"
#define CONSOLE_RESET_GAME "RESET"

typedef BOOL (*CONSOLE_CALLBACK)(char*);
//vector<char *> STRTOK(){
//	_asm{
//		mov eax, 
//	}
//}
static CONSOLE_CALLBACK CONSOLEPARSER(char *pCommand){
	// LOOKS A FIRST KEYWORD
}
